#!/bin/bash

##################################################################
#                                                                #
# Copyright (c) 2018-2022 PrimeKey Solutions AB.                 #
#                                                                #
# This software is free software; you can redistribute it and/or #
# modify it under the terms of the GNU Lesser General Public     #
# License as published by the Free Software Foundation; either   #
# version 2.1 of the License, or any later version.              #
#                                                                #
# See terms of license at gnu.org.                               #
#                                                                #
##################################################################

baseDir="$1"
tempDir="$2"

# Configure the Connector
if [ "$YUBIHSM_CONNECTOR" != "http://localhost:12345" ] ; then
  sed -i "s|^connector = http://localhost:12345|connector = ${YUBIHSM_CONNECTOR}|g" "$YUBIHSM_PKCS11_CONF"   
fi

### Set up env

# Logging
if [ "$YUBIHSM_DEBUG" == "true" ] ; then
  sed -i "s|^# debug|debug|g" "$YUBIHSM_PKCS11_CONF"
fi

if [ "$YUBIHSM_STDOUT" == "true" ] ; then
  sed -i "s|^# debug-file = /dev/stdout|debug-file = /dev/stdout|g" "$YUBIHSM_PKCS11_CONF"
fi

if [ "$YUBIHSM_DINOUT" == "true" ] ; then
  sed -i "s|^# dinout|dinout|g" "$YUBIHSM_PKCS11_CONF"
fi

if [ "$YUBIHSM_LIBDEBUG" == "true" ] ; then
  sed -i "s|^# libdebug|libdebug|g" "$YUBIHSM_PKCS11_CONF"
fi

# Use CA cert
if [ "$YUBIHSM_CACERT" != "false" ] ; then
  sed -i "s|^# cacert = /tmp/cacert.pem|cacert = $YUBIHSM_CACERT|g" "$YUBIHSM_PKCS11_CONF"
fi

# Use a proxy
if [ "$YUBIHSM_PROXY" != "false" ] ; then
  sed -i "s|^# proxy = http://proxyserver.local.com:8080|proxy = $PROXY|g" "$YUBIHSM_PKCS11_CONF"
fi

# Set a timeout (Number)
if [ -n "$YUBIHSM_TIMEOUT" ] && [ "$YUBIHSM_TIMEOUT" -eq "$YUBIHSM_TIMEOUT" ] 2>/dev/null; then
  sed -i "s|^# timeout = 5|timeout = $YUBIHSM_TIMEOUT|g" "$YUBIHSM_PKCS11_CONF"
fi

# Also consumed by the p11proxy-server
export HSM_PKCS11_LIBRARY="${HSM_PKCS11_LIBRARY:-/usr/lib64/pkcs11/yubihsm_pkcs11.so}"

#export HSM_PKCS11_LIBRARY="${HSM_PKCS11_LIBRARY:-/usr/lib64/pkcs11/p11-kit-trust.so}"
#export YUBIHSM_PKCS11_MODULE=$HSM_PKCS11_LIBRARY
