###
### Download/unpack/build HSM library
###

FROM registry.access.redhat.com/ubi8/ubi-minimal:8.4 as builder

WORKDIR /build

RUN \
    microdnf install -y automake diffutils expat-devel file gcc-c++ glibc-static gettext git gzip help2man libtool libxslt libxslt-devel make man ncurses-devel openssl-devel perl-devel tar unzip xz zip --nodocs && \
    microdnf clean all

RUN \
    curl --silent -D - -L "https://github.com/opendnssec/SoftHSMv2/archive/refs/tags/2.6.1.tar.gz" -o SoftHSMv2-current.tar.gz && \
    sha256sum SoftHSMv2-current.tar.gz | grep e3daff28b164611b1f080401d4d70edd0944f692385a7ef75eba5ce056c8c9ca && \
    mkdir -p /build/softhsmv2 && \
    tar -xf SoftHSMv2-current.tar.gz -C "/build/softhsmv2" --strip-components=1 && \
    ls -la && \
    cd softhsmv2/ && \
    ./autogen.sh && \
    ./configure --disable-non-paged-memory --prefix=/usr && \
    make -s && \
    make -s install

###
### Package hsm-driver-softhsm
###

FROM registry.primekey.com/primekey/hsm-driver-base:0.4.25

# Run build as root
USER 0:0

WORKDIR /build

COPY --from=builder /usr/lib64/softhsm/libsofthsm2.so /usr/lib64/softhsm/libsofthsm2.so
COPY --from=builder /usr/bin/softhsm2-keyconv         /usr/bin/
COPY --from=builder /usr/bin/softhsm2-util            /usr/bin/
COPY --from=builder /usr/bin/softhsm2-dump-file       /usr/bin/
COPY --from=builder /var/lib/softhsm/                 /var/lib/softhsm/

COPY --chown=10001:0  opt/softhsm/ /opt/softhsm/

RUN \
    ln -s /usr/lib64/softhsm/libsofthsm2.so /usr/lib64/libsofthsm2.so && \
    chgrp -R 0   /var/lib/softhsm/ /opt/softhsm/ && \
    chmod -R g=u /var/lib/softhsm/ /opt/softhsm/ && \
    rm -rf /build/* && \
    microdnf clean all && \
    rm -rf /var/cache/yum && \
    chown -R 10001:0 /var/lib/softhsm/tokens

# Provide a VOLUME for the --volumes-from pattern
VOLUME /opt/primekey/p11proxy-client/

# Expose environment variables as documentation of how the driver behavior can be modified.

# Log level: DEBUG, INFO, WARNING, ERROR
# Note that since SoftHSM2 only uses syslog for logging this is pointless in an unprivileged container
ENV SOFTHSM2_LOG_LEVEL=INFO

# Location of configuration file
ENV SOFTHSM2_CONF="/opt/softhsm/softhsm2.conf"

# Privilege recommendation (unprivileged user belonging to the root group) for execution.
USER 10001:0

# This is where SoftHSM2 stores slot content that it should kept during upgrades.
# We don't want to expose this as a VOLUME to prevent that the key material is exposed in the client container.
#VOLUME /var/lib/softhsm/tokens/

WORKDIR /opt

# Use the start script from the base container and override setup using the environment-hsm file
#CMD [...]
